### PR TITLE
Fix Neovim issues with v:t_ variables

### LINKED ISSUE #1: E121: Undefined variable: v:t_none
Looks like `v:t_none` is not defined here https://github.com/amadeus/vim-convert-color-to/blob/5c43624386056541fd84caa156f42eb94a967e5e/plugin/colors.vim#L270

```
Error detected while processing function ConvertColorTo[22]..<SNR>70_ConvertColor:
line    2:
E121: Undefined variable: v:t_none
E15: Invalid expression: type(l:data) == v:t_none
```

### PR DESCRIPTION
**Pull request by amadeus**
Fixes #1

Hopefully!

### CODE REVIEW

**Comment by lukas-reineke** [comment]
Neovim doesn't have `v:none` either
But `v:null` works (they have the same type in Vim anyways)

**Comment by amadeus** [comment]
Derp. Just changed it to v:null

**Comment by lukas-reineke** [comment]
Works now. Thanks!

**Comment by amadeus** [comment]
Thx for lookin out!

**Pull request merged**
